<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Properties -->
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <!-- Base footprint -->
    <link name="base_footprint" />

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <!-- Macro for a wheel -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <!-- 4 Wheels -->
    <xacro:wheel_link prefix="rear_right" />
    <xacro:wheel_link prefix="rear_left" />
    <xacro:wheel_link prefix="front_right" />
    <xacro:wheel_link prefix="front_left" />

    <!-- Joints -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- Front Wheels (controlled directly) -->
    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="${base_length / 2.5} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="${base_length / 2.5} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <!-- Rear Wheels (MIMIC joints) -->
    <joint name="base_rear_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_right_wheel_link" />
        <origin xyz="${-base_length / 2.5} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <mimic joint="base_front_right_wheel_joint" multiplier="1.0" />
    </joint>

    <joint name="base_rear_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_left_wheel_link" />
        <origin xyz="${-base_length / 2.5} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <mimic joint="base_front_left_wheel_joint" multiplier="1.0" />
    </joint>

</robot>
