joint_state_broadcaster:
  ros__parameters:
    update_rate: 50

arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - arm_base_forearm_joint
      - forearm_hand_joint
      - left_finger_joint
      - right_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    type: effort_controllers/JointGroupEffortController
    joints:
      - left_finger_joint
      - right_finger_joint
